### ISSUE TITLE
extractorapp - do not remove imageio-ext-gdalframework-1.1.7.jar

### ISSUE THREAD

**Issue by fvanderbiest** [fvanderbiest/georchestra-docker-ci#18]
Pierre says it is required, even if it calls LoadLibrary
so, do not RUN rm -rf /var/lib/tomcat7/webapps/extractorapp/WEB-INF/lib/imageio-ext-gdalframework-1.1.7.jar

**Comment by pmauduit** [comment]
I guess we should fork the module and ask for a specific georchestra version of the jar in the pom (with no system.loadLibrary() call)
