### ISSUE TITLE
Broken Url

### ISSUE THREAD

**Issue by doublebyte1** [fvanderbiest/georchestra-docker-ci#31]
During the setup of docker-orchestra (docker-compose up), it attempts to download this file:

RUN wget --no-check-certificate https://raw.githubusercontent.com/georchestra/georchestra/master/mapfishapp/database.sql -O /tmp/mapfishapp.sql

But the url is not resolved:   ERROR 404: Not Found.

Broken link?

**Comment by fvanderbiest** [comment]
Correct, this repository is now deprecated.

Instead you should use the composition of docker images brought by the main repo https://github.com/georchestra/georchestra (see the docker-compose.yml at the root)

This will download images from the georchestra docker hub.
If you want to build the images by yourself, be sure to follow this procedure: https://github.com/georchestra/georchestra/blob/15.12/doc/build.md#alternative-building-process-using-docker-experimental, before invoking `docker-compose up`.

**Comment by doublebyte1** [comment]
Hi,
Thanks for pointing that out!

**Comment by fvanderbiest** [comment]
You're welcome.

Feel free to join us on irc.freenode.net #georchestra in case you need help setting up the stack.
https://kiwiirc.com/client/irc.freenode.net/georchestra
