### ISSUE TITLE
Service geoserver failed to build: symbolic link to jai_core.jar

### ISSUE THREAD

**Issue by bchartier** [fvanderbiest/georchestra-docker-ci#9]
I've stricly follow the install process decrsibed in the readme file.
It ended with:

> Step 16 : RUN ln -s /usr/share/java/jai_core.jar /usr/share/tomcat7/lib/jai_core.jar
>  ---> Running in e3f3edde6cf9
> ln: failed to create symbolic link '/usr/share/tomcat7/lib/jai_core.jar': File exists
> Service 'geoserver' failed to build: The command [/bin/sh -c ln -s /usr/share/java/jai_core.jar /usr/share/tomcat7/lib/jai_core.jar] returned a non-zero code: 1

Any idea of how to fix this?

**Comment by fvanderbiest** [comment]
This was fixed yesterday evening: https://github.com/georchestra/docker/commit/650e11f068a0715e340d02a75926b63e9b698ddd
